# Generated by Django 5.1.3 on 2024-12-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
    ]
