# Generated by Django 5.1.3 on 2024-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_course_review_semester_subject_userreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='content',
            new_name='module',
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(null=True, upload_to='course_image'),
        ),
    ]
