# Generated by Django 5.1.3 on 2024-12-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_rename_content_subject_module_subject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
