# Generated by Django 5.1.3 on 2024-12-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_subject_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='module',
            new_name='content',
        ),
    ]
