# Generated by Django 5.1.3 on 2025-01-07 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_rename_module_subject_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='content',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='summary',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to='subject_content/')),
                ('summary', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.subject')),
            ],
        ),
    ]
