# Generated by Django 5.1.4 on 2025-01-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_remove_subject_content_remove_subject_summary_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='summary',
        ),
    ]
