# Generated by Django 5.1.4 on 2025-01-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0012_alter_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
