# Generated by Django 5.1.4 on 2025-01-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0013_alter_course_description_alter_module_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
    ]
