# Generated by Django 5.1.4 on 2025-01-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0017_alter_module_subject_alter_subject_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('questions', models.FileField(upload_to='Questions')),
            ],
        ),
    ]
